### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by cqfd**
Just using this as a place to accumulate comments.

### CODE REVIEW

**Comment by cqfd** [comment]
I got confused where you talk about associativity/commutativity.

**Comment by cqfd** [comment]
About the Topecky suggestion for `h`, I would rather just say "It turns out[footnote] that a good choice for `h` is...". I don't really understand how the Taylor series idea helps us.

**Comment by cqfd** [comment]
At the beginning of the jump to complex analysis, I would want to motivate even more just how remarkable it is that complex numbers could help: if you had asked me how to compute a derivative in any way besides a finite difference, I would have come up totally blank. How could there possibly be any other way?

**Comment by cqfd** [comment]
Totally lost me in the Hack the Derivative section :) Why are we talking about z bar all of a sudden? I agree that if z = x + i y and z bar is in R, then y = 0. I imagine that we're taking our regular old real valued function and "extending" it to the complex plane, and I assume that that extension happens by just plugging complex numbers into a function's Taylor expansion (if f(x) = x^2, you're already a polynomial, all good, but for sin(x) you'd use the Taylor expansion).

We're then going to use the Cauchy-Riemann equations to get a novel expression for the derivative, Im(f(x + i h))/h as h goes to zero. That's cool. But is there any intuition for why this would work so well? I lose the thread here--I see the algebra you're doing, but I wouldn't have guessed that this has nice properties.

**Comment by eriktaubeneck** [comment]
Merged this, and added edits to master. Some notes:
- Agreed on the Taylor Series. Took it out and left a comment that the reader could look into if they wanted.
- Tried to make the point about multiplication precision vs addition precision more clear.
- Agreed on the footnote, done.
- Added a little bit more to motivate complex analysis, but not sure how much more I can put there. There  are other ways of taking the derivative (automatic differentiation, for example), but I'm not sure that's worth getting into at that spot.
- Tried to add some more motivation in the Hack the Derivative section, particularly pointing out where we get rid of the subtraction that is the culprit of the loss of floating point accuracy. (Probably why the associative/commutative wasn't super clear earlier.) Hopefully that's more clear now.

**Pull request merged**
